FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD restaurant.jar /opt/restaurant/
EXPOSE 8080
WORKDIR /opt/restaurant/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "restaurant.jar"]
